set(XDIRECTORIESX "DW1000" "BRDCFG")

foreach(XDIRECTORYX IN LISTS XDIRECTORIESX)
    file(GLOB_RECURSE XSUBDIRSX LIST_DIRECTORIES true "${CMAKE_SOURCE_DIR}/${XDIRECTORYX}/*")
    list(APPEND XSUBDIRSX "${CMAKE_SOURCE_DIR}/${XDIRECTORYX}")
    set(XHEADERDIRSX "")

    foreach(XSUBDIRX IN LISTS XSUBDIRSX)
        if(IS_DIRECTORY "${XSUBDIRX}")
            list(APPEND XHEADERDIRSX "${XSUBDIRX}")
        endif()
    endforeach()

    list(REMOVE_DUPLICATES XHEADERDIRSX)
    target_include_directories(${CMAKE_PROJECT_NAME} PRIVATE ${XHEADERDIRSX})
    file(GLOB_RECURSE XSOURCFILESX "${CMAKE_SOURCE_DIR}/${XDIRECTORYX}/*.c")
    target_sources(${CMAKE_PROJECT_NAME} PRIVATE ${XSOURCFILESX})
endforeach()
