file(GLOB_RECURSE STM32_SUBDIRS LIST_DIRECTORIES true "${CMAKE_CURRENT_SOURCE_DIR}/*")
list(APPEND STM32_SUBDIRS "${CMAKE_CURRENT_SOURCE_DIR}")
set(STM32_HEADER_DIRS "")

foreach(STM32_SUBDIR IN LISTS STM32_SUBDIRS)
    if(IS_DIRECTORY "${STM32_SUBDIR}")
        list(APPEND STM32_HEADER_DIRS "${STM32_SUBDIR}")
    endif()
endforeach()

list(REMOVE_DUPLICATES STM32_HEADER_DIRS)
target_include_directories(${CMAKE_PROJECT_NAME} SYSTEM PRIVATE ${STM32_HEADER_DIRS})

file(GLOB_RECURSE STM32_SOURCE_FILES "${CMAKE_CURRENT_SOURCE_DIR}/*.c" "${CMAKE_CURRENT_SOURCE_DIR}/*.s")
target_sources(${CMAKE_PROJECT_NAME} PRIVATE ${STM32_SOURCE_FILES})
set_source_files_properties(${STM32_SOURCE_FILES} PROPERTIES COMPILE_FLAGS "-Wno-conversion -Wno-unused-parameter")